# Generated by Django 3.1.7 on 2021-03-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0004_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_product',
            new_name='orderProduct',
        ),
    ]
